using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;

namespace CardAccess
{
    class PythonAccess : IPythonAccess
    {
        public IList<string> Execute(ScriptName script, string arguments = "")
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "sudo";
            start.Arguments = string.Format("\"{0}\" \"PythonScripts/{1}.py\" {2}", "python3", script.ToString().ToLower(), arguments);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result.Split(Environment.NewLine, StringSplitOptions.RemoveEmptyEntries);
                }
            }
        }
    }
}
